controllers/SalaController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Reserva;
use app\models\SalaHorario;
use app\models\SalaSearch;
use app\models\Sala;
use yii\filters\VerbFilter;

class SalaController extends Controller
{
    
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['listar', 'alterar', 'deletar', 'criar', 'agendar', 'cancelar'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['agendar', 'cancelar'],
                        'matchCallback' => function ($rule, $action) {
                            return (!Yii::$app->user->isGuest);
                        }
                    ],
                    [
                        'allow' => true,
                        'actions' => ['listar', 'criar', 'alterar', 'deletar'],
                        'matchCallback' => function ($rule, $action) {
                            return ((!Yii::$app->user->isGuest) && (Yii::$app->user->identity->perfil_id == 1));
                        }
                    ],
                ],
            ],
        ];
    }
    
    public function actionListar()
    {
        $searchModel = new SalaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('listar', [
            'dataProvider' => $dataProvider,
        ]);
        
    }
    
    public function actionCriar()
    {
        $model = new Sala();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'A sala foi criada com sucesso.');
                return $this->redirect(['listar']);
            }
        }
        return $this->render('criar', [
            'model' => $model
        ]);
    }
    
    public function actionAlterar($id)
    {
        $model = Sala::findOne(['id' => $id]);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'O nome da sala foi alterada com sucesso.');
                return $this->redirect(['listar']);
            }
        }
        return $this->render('alterar', [
            'model' => $model
        ]);
    }
    
    public function actionDeletar($id)
    {
        $sala = Sala::findOne(['id' => $id]);
        if ($sala) {
            $sala->ativo = 0;
            if ($sala->save()) {
                Yii::$app->session->setFlash('success', 'A sala foi deletada com sucesso.');
            }
        }
        return $this->redirect(['listar']);
    }

    public function actionAgendar($id)
    {
        $usuario_id = Yii::$app->user->identity->id;
        $sala_horario = SalaHorario::findOne(['id' => $id]);
        if ($sala_horario) {
            $reserva = new Reserva();
            $reserva->sala_id = $sala_horario->sala_id;
            $reserva->sala_horario_id = $id;
            $reserva->usuario_id = $usuario_id;
            if ($reserva->save()) {
                Yii::$app->session->setFlash('success', 'O horário da sala foi reservado com sucesso.');
            }
        }
        return $this->redirect(['site/index']);
    }
    
    public function actionCancelar($id)
    {
        $usuario_id = Yii::$app->user->identity->id;
        $reserva = Reserva::findOne(['id' => $id]);
        if ($reserva) {
            $reserva->delete();
            Yii::$app->session->setFlash('success', 'O horário reservado da sala foi cancelado com sucesso.');
        }
        return $this->redirect(['site/index']);
    }
}

controllers/UsuarioController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Usuario;
use app\models\UsuarioSearch;
use yii\filters\VerbFilter;

class UsuarioController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['listar', 'criar', 'alterar', 'deletar'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['listar', 'criar', 'alterar', 'deletar'],
                        'matchCallback' => function ($rule, $action) {
                            return ((!Yii::$app->user->isGuest) && (Yii::$app->user->identity->perfil_id == 1));
                        }
                    ],
                ],
            ],
        ];
    }
    
    public function actionListar()
    {
        $searchModel = new UsuarioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('listar', [
            'dataProvider' => $dataProvider,
        ]);
        
    }
    
    public function actionCriar()
    {
        $model = new Usuario();
        if ($model->load(Yii::$app->request->post())) {
            if (empty($model->password)) {
                Yii::$app->session->setFlash('error', 'A senha é obrigatório.');
            } else {
                $model->password = md5($model->password);
                $model->authkey = md5($model->username.''.time());
                if ($model->save()) {
                    Yii::$app->session->setFlash('success', 'O usuário foi criado com sucesso.');
                    return $this->redirect(['listar']);
                }
            }
        }
        return $this->render('criar', [
            'model' => $model
        ]);
    }
    
    public function actionAlterar($id)
    {
        $model = Usuario::findOne(['id' => $id]);
        if (Yii::$app->request->post()) {
            $post = Yii::$app->request->post();
            $nome = $post["Usuario"]["nome"];
            $username = $post["Usuario"]["username"];
            $password = $post["Usuario"]["password"];
            $perfil_id = $post["Usuario"]["perfil_id"];
            
            $model->nome = $nome;
            $model->username = $username;
            $model->perfil_id = $perfil_id;

            if (!empty($password)) {
                $model->password = md5($password);
            }
            
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'O usuário foi atualizado com sucesso.');
                return $this->redirect(['listar']);
            }
        }
        $model->password = '';
        return $this->render('alterar', [
            'model' => $model
        ]);
    }
    
    public function actionDeletar($id)
    {
        $usuario = Usuario::findOne(['id' => $id]);
        if ($usuario) {
            $usuario->ativo = 0;
            if ($usuario->save()) {
                Yii::$app->session->setFlash('success', 'O usuário foi deletado com sucesso.');
            }
        }
        return $this->redirect(['listar']);
    }
}

views/layouts/main.php
<?php
use app\widgets\Alert;
use yii\helpers\Html;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<?php $this->title = 'Sistema de Agendamento'; ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
    <head>
        <meta charset="<?= Yii::$app->charset ?>">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <?= Html::csrfMetaTags() ?>
        <title><?= Html::encode($this->title) ?></title>
        <?php $this->head() ?>
    </head>
    <body>
    <?php $this->beginBody() ?>
    <div class="wrap">
        <?php $controller = Yii::$app->controller->id; ?>
        <?php $action = Yii::$app->controller->action->id ?>
        <?php if ($controller.'/'.$action !== 'site/login') { ?>
            <div id="throbber" class="throbber-fix"></div>
            <div id="noty-holder"></div>
            <div id="wrapper">
                <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <div>teste</div>
                    </div>
                    <ul class="nav navbar-right top-nav margin-right-20">
                        <li class="dropdown">
                            <div class="btn-logout">
                            <?= Html::a('Logout', ['site/logout'], ['class' => 'btn btn-danger']); ?>
                            </div>
                        </li>
                    </ul>
                    <ul class="nav navbar-right top-nav">
                        <li class="dropdown">
                            <div class="bemvindo-usuario">
                                <span class="glyphicon glyphicon-user"></span>
                                <span> Olá <?= Yii::$app->user->identity->nome; ?></span>
                            </div>
                        </li>
                    </ul>
                    <ul class="nav navbar-left top-nav">
                        <li class="dropdown">
                            <div class="titulo-header">Sistema de Agendamento</div>
                        </li>
                    </ul>
                    <div class="collapse navbar-collapse navbar-ex1-collapse">
                        <ul class="nav navbar-nav side-nav">
                            <li>
                                <?= Html::a('Salas', ['site/index']); ?>
                            </li>
                            <?php if ((!Yii::$app->user->isGuest) && (Yii::$app->user->identity->perfil_id == 1)) { ?>
                                <li>
                                    <?= Html::a('Gerenciar Salas', ['sala/listar']); ?>
                                </li>
                                <li>
                                    <?= Html::a('Gerenciar Usuários', ['usuario/listar']); ?>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </nav>
                <div id="page-wrapper">
                    <div class="container-fluid">
                        <div class="row" id="main" >
                            <div class="col-sm-12 col-md-12" id="content">
                                <?= Alert::widget() ?>
                                <?= $content ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        <?php } else { ?>
            <div class="container"> 
                <?= Alert::widget() ?> 
                <?= $content ?> 
            </div>
        <?php } ?>
    </div>
    <footer class="footer">
        <div class="container"></div>
    </footer>
    <?php $this->endBody() ?>
    </body>
</html>
<?php $this->endPage() ?>