models/SalaHorario.php
<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "sala_horario".
 *
 * @property string $id
 * @property string $sala_id
 * @property string $inicio
 * @property string $fim
 * @property string $data
 * @property integer $ativo
 *
 * @property Sala $sala
 */
class SalaHorario extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'sala_horario';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['sala_id', 'ativo'], 'integer'],
            [['inicio', 'fim', 'data'], 'safe'],
            [['sala_id'], 'exist', 'skipOnError' => true, 'targetClass' => Sala::className(), 'targetAttribute' => ['sala_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'sala_id' => 'Sala',
            'inicio' => 'Inicio',
            'fim' => 'Fim',
            'data' => 'Data',
            'ativo' => 'Ativo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSala()
    {
        return $this->hasOne(Sala::className(), ['id' => 'sala_id']);
    }
    
    public function getHoraIniciofim()
    {
        $inicio = date('H:i', strtotime($this->inicio));
        $fim = date('H:i', strtotime($this->fim));
        return $inicio.'-'.$fim;
    }
    
    /**
     * Retorna o status do horário da sala.
     * 
     * @return string
     */
    public function getStatus()
    {
        $status = 'Disponível';
        $reserva_id = $this->id;
        $sala_id = $this->sala_id;
        $usuario_id = Yii::$app->user->identity->id;
        
        $reserva = Reserva::find()
            ->where(['sala_horario_id' => $reserva_id])
            ->andWhere(['sala_id' => $sala_id])
            ->one();
        if ($reserva) {
            if ($reserva->usuario_id == $usuario_id) {
                $status = 'Agendado';
            } else {
                $status = 'Bloqueado';
            }
        }
        
        return $status;
    }
    
    /**
     * Retorna o ID de da reserva.
     * 
     * @return integer
     */
    public function getUsuarioReservaId()
    {
        $reserva_id = $this->id;
        $sala_id = $this->sala_id;
        $usuario_id = Yii::$app->user->identity->id;
        $reserva = Reserva::find()
            ->innerJoin('sala_horario', 'sala_horario.id = reserva.sala_horario_id')
            ->where(['sala_horario_id' => $reserva_id])
            ->andWhere(['reserva.sala_id' => $sala_id])
            ->andWhere(['usuario_id' => $usuario_id])
            ->andWhere(['data' => date('Y-m-d')])
            ->one();
        return $reserva->id;
    }
    
    /**
     * Retorna o nome do usuário que fez o agendamento da sala.
     * 
     * @return string
     */
    public function getAgendadorNome()
    {
        $nome = '';
        $reserva_id = $this->id;
        $sala_id = $this->sala_id;
        $reserva = Reserva::find()
            ->innerJoin('sala_horario', 'sala_horario.id = reserva.sala_horario_id')
            ->where(['sala_horario_id' => $reserva_id])
            ->andWhere(['reserva.sala_id' => $sala_id])
            ->andWhere(['data' => date('Y-m-d')])
            ->one();
        if ($reserva) {
            $nome = $reserva->usuario->nome;
        }
        
        return $nome;
    }
}

controllers/SalaController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\Reserva;
use app\models\SalaHorario;
use app\models\SalaSearch;
use app\models\Sala;
use yii\filters\VerbFilter;

class SalaController extends Controller
{
    
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'only' => ['listar', 'alterar', 'deletar', 'criar', 'agendar', 'cancelar'],
                'rules' => [
                    [
                        'allow' => true,
                        'actions' => ['agendar', 'cancelar'],
                        'matchCallback' => function ($rule, $action) {
                            return (!Yii::$app->user->isGuest);
                        }
                    ],
                    [
                        'allow' => true,
                        'actions' => ['listar', 'criar', 'alterar', 'deletar'],
                        'matchCallback' => function ($rule, $action) {
                            return ((!Yii::$app->user->isGuest) && (Yii::$app->user->identity->perfil_id == 1));
                        }
                    ],
                ],
            ],
        ];
    }
    
    public function actionListar()
    {
        $searchModel = new SalaSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        
        return $this->render('listar', [
            'dataProvider' => $dataProvider,
        ]);
        
    }
    
    public function actionCriar()
    {
        $model = new Sala();
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'A sala foi criada com sucesso.');
                return $this->redirect(['listar']);
            }
        }
        return $this->render('criar', [
            'model' => $model
        ]);
    }
    
    public function actionAlterar($id)
    {
        $model = Sala::findOne(['id' => $id]);
        if ($model->load(Yii::$app->request->post())) {
            if ($model->save()) {
                Yii::$app->session->setFlash('success', 'O nome da sala foi alterada com sucesso.');
                return $this->redirect(['listar']);
            }
        }
        return $this->render('alterar', [
            'model' => $model
        ]);
    }
    
    public function actionDeletar($id)
    {
        $sala = Sala::findOne(['id' => $id]);
        if ($sala) {
            $sala->ativo = 0;
            if ($sala->save()) {
                Yii::$app->session->setFlash('success', 'A sala foi deletada com sucesso.');
            }
        }
        return $this->redirect(['listar']);
    }

    public function actionAgendar($id)
    {
        $usuario_id = Yii::$app->user->identity->id;
        $sala_horario = SalaHorario::findOne(['id' => $id]);
        if ($sala_horario) {
            $reserva = new Reserva();
            $reserva->sala_id = $sala_horario->sala_id;
            $reserva->sala_horario_id = $id;
            $reserva->usuario_id = $usuario_id;
            if ($reserva->save()) {
                Yii::$app->session->setFlash('success', 'O horário da sala foi reservado com sucesso.');
            }
        }
        return $this->redirect(['site/index']);
    }
    
    public function actionCancelar($id)
    {
        $usuario_id = Yii::$app->user->identity->id;
        $reserva = Reserva::findOne(['id' => $id]);
        if ($reserva) {
            $reserva->delete();
            Yii::$app->session->setFlash('success', 'O horário reservado da sala foi cancelado com sucesso.');
        }
        return $this->redirect(['site/index']);
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use app\models\LoginForm;
use app\models\Sala;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        if (Yii::$app->user->isGuest) {
            return $this->redirect(['login']);
        }
        
        $salas = Sala::find()
            ->where(['ativo' => 1])
            ->all();
        
        return $this->render('index',[
            'salas' => $salas
        ]);
    }

    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        
        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['index']);
        } else {
            if ($model->getErrors()) {
                $data = $model->getErrors();
                Yii::$app->session->setFlash('error', $data['password'][0]);
            }
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();
        return $this->goHome();
    }
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/index.php
<?php
use yii\helpers\Html;

$this->title = 'Sistema de Agendamento';
?>
<div class="site-index">
    <div class="body-content">
        <div class="row">
            <div class="col-sm-12">
                <div class="titulo-pagina">Salas</div>
            </div>
        </div>
        <hr>
        <div class="row">
            <?php foreach ($salas as $sala) { ?>
                <div class="col-sm-4">
                    <ul class="list-group">
                        <li class="list-group-item active">
                            <span><?= $sala->nome; ?></span>
                            <span class="float-right"><?= date('d/m/Y'); ?></span>
                        </li>
                        <li class="list-group-item active font-12">
                            <div class="row">
                                <div class="col-sm-3"><span>Horário</span></div>
                                <div class="col-sm-3 text-center"><div class="agendamento-campos">Status</div></div>
                                <div class="col-sm-3 text-center">Agendado Por</div>
                                <div class="col-sm-3 text-center">Ação</div>
                            </div>
                        </li>
                        <?php foreach ($sala->listaHorariosDia as $horario) {?>
                            <li class="list-group-item <?= ($horario->status == 'Agendado')?'list-group-item-info':''; ?> font-12">
                                <div class="row">
                                    <div class="col-sm-3"><div class="agendamento-campos"><?= $horario->horaInicioFim ?></div></div>
                                    <div class="col-sm-3 text-center"><div class="agendamento-campos"><?= $horario->status; ?></div></div>
                                    <div class="col-sm-3 text-center"><?= $horario->agendadorNome; ?></div>
                                    <div class="col-sm-3 text-center">
                                        <?php if ($horario->status == 'Disponível') { ?>
                                            <?= Html::a('Agendar', ['sala/agendar', 'id' => $horario->id], [
                                                'class' => 'btn btn-primary btn-xs',
                                                'data-confirm' => "Reservar a sala '".$sala->nome."' no horário '".$horario->horaInicioFim."'?",
                                            ]); ?>
                                        <?php } elseif ($horario->status == 'Agendado') { ?>
                                            <?php $reserva_id = $horario->usuarioReservaId; ?>
                                            <?= Html::a('Cancelar', ['sala/cancelar', 'id' => $reserva_id], [
                                                'class' => 'btn btn-danger btn-xs',
                                                'data-confirm' => "Cancelar a reserva da sala '".$sala->nome."' no horário '".$horario->horaInicioFim."'?",
                                            ]); ?>
                                        <?php } ?>
                                    </div>
                                </div>
                            </li>
                        <?php } ?>
                    </ul>
                </div>
            <?php } ?>
        </div>
    </div>
</div>

views/site/login.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

$this->title = 'Sistema de Agendamento';
?>
<div class="container">
    <div class="row">
        <div class="col-md-3 col-md-offset-4">
            <div class="panel panel-login">
                <div class="panel-heading">
                    <div class="row">
                        <div class="col-xs-12 text-center">
                            <h4 class="active2">Sistema de Agendamento</h4>
                        </div>
                    </div>
                    <hr>
                </div>
                <div class="panel-body">
                    <?php $form = ActiveForm::begin([
                        'id' => 'login-form',
                        'layout' => 'horizontal',
                        'fieldConfig' => [
                            'template' => "{label}\n<div class=\"col-sm-12\">{input}</div>",
                            'labelOptions' => ['class' => 'col-lg-1 control-label'],
                        ],
                    ]); ?>
                    <div class="row">
                        <div class="col-lg-12">
                            <form id="login-form" method="post" role="form" style="display: block;">
                                <div class="form-group">
                                    <?= $form->field($model, 'username', [
                                        'inputOptions' => [
                                            'class' => 'form-control',
                                            'tabindex' => '1',
                                            'placeholder' => 'Usuário',
                                            'enableClientValidation' => false
                                        ]])->textInput(['class'=>'form-control'])->label(false); ?>
                                </div>
                                <div class="form-group">
                                    <?= $form->field($model, 'password', [
                                        'inputOptions' => [
                                            'class' => 'form-control',
                                            'tabindex' => '2',
                                            'placeholder' => 'Senha',
                                            'enableClientValidation' => false
                                        ]])->passwordInput()->label(false); ?>
                                </div>
                                <div class="form-group">
                                    <div class="row">
                                        <div class="col-sm-6 col-sm-offset-3">
                                            <?= Html::submitButton('Entrar', ['class' => 'form-control btn btn-primary', 'name' => 'login-button']); ?>
                                        </div>
                                    </div>
                                </div>
                            </form>
                       </div>
                    </div>
                    <?php ActiveForm::end(); ?>
                </div>
            </div>
        </div>
    </div>
</div>